version: '2.3'

services:
  limo:
    container_name: limo
    build:
      context: ./src
    image: ros:melodic-perception
    command: bash
    ports:
      - 8888:8888
    volumes:
      # - $HOME/limo_data:/limo_data
      - ..:/workspace/limo_ws/src/limo
      - $HOME/data/Dataset:/limo_data
    stdin_open: true
    tty: true
    network_mode: "host"
